In [1]:
####################
# Testing the OGLE 3 DNN
####################

import numpy as np
import glob

from tensorflow import keras
from tensorflow.keras.preprocessing import image

float_formatter = lambda x: "%.2f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

In [2]:
model = keras.models.load_model('../OGLE3_DNN_results/OGLE3_colored.h5')
# model = Sequential(model)

In [18]:
dir = "../testdata_color/"
datafiles = []
datafiles = sorted(glob.glob(dir + "t2cep_*.png"))

# datafiles = ["../testdata_nocolor/acep_001.png"]

print("Number of samples: ", len(datafiles))


Number of samples:  2441


In [4]:
datafiles[1]

'../testdata_nocolor/ecl_30002.png'

In [19]:
prediction = np.array([0,0,0,0,0])

for img in datafiles:
    print(img)
    img_size = 128
    # img = cv2.imread(img)
    # img = cv2.resize(img,(img_size,img_size))

    # img = np.expand_dims(img, axis=0)

    # model.predict(img)
    img = image.load_img(img, target_size=(img_size, img_size))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
#     print(model.predict(img))
    prediction = prediction + model.predict(img)
    # model.predict_classes(img)

print(prediction)

../testdata_color/t2cep_001.png
../testdata_color/t2cep_001_clone_0.png
../testdata_color/t2cep_001_clone_1.png
../testdata_color/t2cep_001_clone_2.png
../testdata_color/t2cep_001_clone_3.png
../testdata_color/t2cep_001_clone_4.png
../testdata_color/t2cep_001_clone_5.png
../testdata_color/t2cep_001_clone_6.png
../testdata_color/t2cep_001_clone_7.png
../testdata_color/t2cep_002.png
../testdata_color/t2cep_002_clone_0.png
../testdata_color/t2cep_002_clone_1.png
../testdata_color/t2cep_002_clone_2.png
../testdata_color/t2cep_002_clone_3.png
../testdata_color/t2cep_002_clone_4.png
../testdata_color/t2cep_002_clone_5.png
../testdata_color/t2cep_002_clone_6.png
../testdata_color/t2cep_002_clone_7.png
../testdata_color/t2cep_003.png
../testdata_color/t2cep_003_clone_0.png
../testdata_color/t2cep_003_clone_1.png
../testdata_color/t2cep_003_clone_2.png
../testdata_color/t2cep_003_clone_3.png
../testdata_color/t2cep_003_clone_4.png
../testdata_color/t2cep_003_clone_5.png
../testdata_color/t2cep_

../testdata_color/t2cep_025_clone_3.png
../testdata_color/t2cep_025_clone_4.png
../testdata_color/t2cep_025_clone_5.png
../testdata_color/t2cep_025_clone_6.png
../testdata_color/t2cep_025_clone_7.png
../testdata_color/t2cep_026.png
../testdata_color/t2cep_026_clone_0.png
../testdata_color/t2cep_026_clone_1.png
../testdata_color/t2cep_026_clone_2.png
../testdata_color/t2cep_026_clone_3.png
../testdata_color/t2cep_026_clone_4.png
../testdata_color/t2cep_026_clone_5.png
../testdata_color/t2cep_026_clone_6.png
../testdata_color/t2cep_026_clone_7.png
../testdata_color/t2cep_027.png
../testdata_color/t2cep_027_clone_0.png
../testdata_color/t2cep_027_clone_1.png
../testdata_color/t2cep_027_clone_2.png
../testdata_color/t2cep_027_clone_3.png
../testdata_color/t2cep_027_clone_4.png
../testdata_color/t2cep_027_clone_5.png
../testdata_color/t2cep_027_clone_6.png
../testdata_color/t2cep_027_clone_7.png
../testdata_color/t2cep_028.png
../testdata_color/t2cep_028_clone_0.png
../testdata_color/t2cep_

../testdata_color/t2cep_050.png
../testdata_color/t2cep_050_clone_0.png
../testdata_color/t2cep_050_clone_1.png
../testdata_color/t2cep_050_clone_2.png
../testdata_color/t2cep_050_clone_3.png
../testdata_color/t2cep_050_clone_4.png
../testdata_color/t2cep_050_clone_5.png
../testdata_color/t2cep_050_clone_6.png
../testdata_color/t2cep_050_clone_7.png
../testdata_color/t2cep_051.png
../testdata_color/t2cep_051_clone_0.png
../testdata_color/t2cep_051_clone_1.png
../testdata_color/t2cep_051_clone_2.png
../testdata_color/t2cep_051_clone_3.png
../testdata_color/t2cep_051_clone_4.png
../testdata_color/t2cep_051_clone_5.png
../testdata_color/t2cep_051_clone_6.png
../testdata_color/t2cep_051_clone_7.png
../testdata_color/t2cep_052.png
../testdata_color/t2cep_052_clone_0.png
../testdata_color/t2cep_052_clone_1.png
../testdata_color/t2cep_052_clone_2.png
../testdata_color/t2cep_052_clone_3.png
../testdata_color/t2cep_052_clone_4.png
../testdata_color/t2cep_052_clone_5.png
../testdata_color/t2cep_

../testdata_color/t2cep_073_clone_4.png
../testdata_color/t2cep_073_clone_5.png
../testdata_color/t2cep_073_clone_6.png
../testdata_color/t2cep_073_clone_7.png
../testdata_color/t2cep_074.png
../testdata_color/t2cep_074_clone_0.png
../testdata_color/t2cep_074_clone_1.png
../testdata_color/t2cep_074_clone_2.png
../testdata_color/t2cep_074_clone_3.png
../testdata_color/t2cep_074_clone_4.png
../testdata_color/t2cep_074_clone_5.png
../testdata_color/t2cep_074_clone_6.png
../testdata_color/t2cep_075.png
../testdata_color/t2cep_075_clone_0.png
../testdata_color/t2cep_075_clone_1.png
../testdata_color/t2cep_075_clone_2.png
../testdata_color/t2cep_075_clone_3.png
../testdata_color/t2cep_075_clone_4.png
../testdata_color/t2cep_075_clone_5.png
../testdata_color/t2cep_075_clone_6.png
../testdata_color/t2cep_075_clone_7.png
../testdata_color/t2cep_076.png
../testdata_color/t2cep_076_clone_0.png
../testdata_color/t2cep_076_clone_1.png
../testdata_color/t2cep_076_clone_2.png
../testdata_color/t2cep_

../testdata_color/t2cep_098_clone_1.png
../testdata_color/t2cep_098_clone_2.png
../testdata_color/t2cep_098_clone_3.png
../testdata_color/t2cep_098_clone_4.png
../testdata_color/t2cep_098_clone_5.png
../testdata_color/t2cep_098_clone_6.png
../testdata_color/t2cep_099.png
../testdata_color/t2cep_099_clone_0.png
../testdata_color/t2cep_099_clone_1.png
../testdata_color/t2cep_099_clone_2.png
../testdata_color/t2cep_099_clone_3.png
../testdata_color/t2cep_099_clone_4.png
../testdata_color/t2cep_099_clone_5.png
../testdata_color/t2cep_099_clone_6.png
../testdata_color/t2cep_099_clone_7.png
../testdata_color/t2cep_100.png
../testdata_color/t2cep_100_clone_0.png
../testdata_color/t2cep_100_clone_1.png
../testdata_color/t2cep_100_clone_2.png
../testdata_color/t2cep_100_clone_3.png
../testdata_color/t2cep_100_clone_4.png
../testdata_color/t2cep_100_clone_5.png
../testdata_color/t2cep_100_clone_6.png
../testdata_color/t2cep_101.png
../testdata_color/t2cep_101_clone_0.png
../testdata_color/t2cep_

../testdata_color/t2cep_125_clone_1.png
../testdata_color/t2cep_125_clone_2.png
../testdata_color/t2cep_125_clone_3.png
../testdata_color/t2cep_125_clone_4.png
../testdata_color/t2cep_125_clone_5.png
../testdata_color/t2cep_125_clone_6.png
../testdata_color/t2cep_125_clone_7.png
../testdata_color/t2cep_126.png
../testdata_color/t2cep_126_clone_0.png
../testdata_color/t2cep_126_clone_1.png
../testdata_color/t2cep_126_clone_2.png
../testdata_color/t2cep_126_clone_3.png
../testdata_color/t2cep_126_clone_4.png
../testdata_color/t2cep_126_clone_5.png
../testdata_color/t2cep_126_clone_6.png
../testdata_color/t2cep_127.png
../testdata_color/t2cep_127_clone_0.png
../testdata_color/t2cep_127_clone_1.png
../testdata_color/t2cep_127_clone_2.png
../testdata_color/t2cep_127_clone_3.png
../testdata_color/t2cep_127_clone_4.png
../testdata_color/t2cep_127_clone_5.png
../testdata_color/t2cep_127_clone_6.png
../testdata_color/t2cep_127_clone_7.png
../testdata_color/t2cep_128.png
../testdata_color/t2cep_

../testdata_color/t2cep_149_clone_7.png
../testdata_color/t2cep_151.png
../testdata_color/t2cep_151_clone_0.png
../testdata_color/t2cep_151_clone_1.png
../testdata_color/t2cep_151_clone_2.png
../testdata_color/t2cep_151_clone_3.png
../testdata_color/t2cep_151_clone_4.png
../testdata_color/t2cep_151_clone_5.png
../testdata_color/t2cep_151_clone_6.png
../testdata_color/t2cep_152.png
../testdata_color/t2cep_152_clone_0.png
../testdata_color/t2cep_152_clone_1.png
../testdata_color/t2cep_152_clone_2.png
../testdata_color/t2cep_152_clone_3.png
../testdata_color/t2cep_152_clone_4.png
../testdata_color/t2cep_152_clone_5.png
../testdata_color/t2cep_152_clone_6.png
../testdata_color/t2cep_152_clone_7.png
../testdata_color/t2cep_153.png
../testdata_color/t2cep_153_clone_0.png
../testdata_color/t2cep_153_clone_1.png
../testdata_color/t2cep_153_clone_2.png
../testdata_color/t2cep_153_clone_3.png
../testdata_color/t2cep_153_clone_4.png
../testdata_color/t2cep_153_clone_5.png
../testdata_color/t2cep_

../testdata_color/t2cep_176_clone_5.png
../testdata_color/t2cep_176_clone_6.png
../testdata_color/t2cep_177.png
../testdata_color/t2cep_177_clone_0.png
../testdata_color/t2cep_177_clone_1.png
../testdata_color/t2cep_177_clone_2.png
../testdata_color/t2cep_177_clone_3.png
../testdata_color/t2cep_177_clone_4.png
../testdata_color/t2cep_177_clone_5.png
../testdata_color/t2cep_177_clone_6.png
../testdata_color/t2cep_177_clone_7.png
../testdata_color/t2cep_178.png
../testdata_color/t2cep_178_clone_0.png
../testdata_color/t2cep_178_clone_1.png
../testdata_color/t2cep_178_clone_2.png
../testdata_color/t2cep_178_clone_3.png
../testdata_color/t2cep_178_clone_4.png
../testdata_color/t2cep_178_clone_5.png
../testdata_color/t2cep_178_clone_6.png
../testdata_color/t2cep_179.png
../testdata_color/t2cep_179_clone_0.png
../testdata_color/t2cep_179_clone_1.png
../testdata_color/t2cep_179_clone_2.png
../testdata_color/t2cep_179_clone_3.png
../testdata_color/t2cep_179_clone_4.png
../testdata_color/t2cep_

../testdata_color/t2cep_201_clone_6.png
../testdata_color/t2cep_201_clone_7.png
../testdata_color/t2cep_203.png
../testdata_color/t2cep_203_clone_0.png
../testdata_color/t2cep_203_clone_1.png
../testdata_color/t2cep_203_clone_2.png
../testdata_color/t2cep_203_clone_3.png
../testdata_color/t2cep_203_clone_4.png
../testdata_color/t2cep_203_clone_5.png
../testdata_color/t2cep_203_clone_6.png
../testdata_color/t2cep_204.png
../testdata_color/t2cep_204_clone_0.png
../testdata_color/t2cep_204_clone_1.png
../testdata_color/t2cep_204_clone_2.png
../testdata_color/t2cep_204_clone_3.png
../testdata_color/t2cep_204_clone_4.png
../testdata_color/t2cep_204_clone_5.png
../testdata_color/t2cep_204_clone_6.png
../testdata_color/t2cep_204_clone_7.png
../testdata_color/t2cep_205.png
../testdata_color/t2cep_205_clone_0.png
../testdata_color/t2cep_205_clone_1.png
../testdata_color/t2cep_205_clone_2.png
../testdata_color/t2cep_205_clone_3.png
../testdata_color/t2cep_205_clone_4.png
../testdata_color/t2cep_

../testdata_color/t2cep_227_clone_3.png
../testdata_color/t2cep_227_clone_4.png
../testdata_color/t2cep_227_clone_5.png
../testdata_color/t2cep_227_clone_6.png
../testdata_color/t2cep_228.png
../testdata_color/t2cep_228_clone_0.png
../testdata_color/t2cep_228_clone_1.png
../testdata_color/t2cep_228_clone_2.png
../testdata_color/t2cep_228_clone_3.png
../testdata_color/t2cep_228_clone_4.png
../testdata_color/t2cep_228_clone_5.png
../testdata_color/t2cep_228_clone_6.png
../testdata_color/t2cep_228_clone_7.png
../testdata_color/t2cep_229.png
../testdata_color/t2cep_229_clone_0.png
../testdata_color/t2cep_229_clone_1.png
../testdata_color/t2cep_229_clone_2.png
../testdata_color/t2cep_229_clone_3.png
../testdata_color/t2cep_229_clone_4.png
../testdata_color/t2cep_229_clone_5.png
../testdata_color/t2cep_229_clone_6.png
../testdata_color/t2cep_230.png
../testdata_color/t2cep_230_clone_0.png
../testdata_color/t2cep_230_clone_1.png
../testdata_color/t2cep_230_clone_2.png
../testdata_color/t2cep_

../testdata_color/t2cep_252_clone_3.png
../testdata_color/t2cep_252_clone_4.png
../testdata_color/t2cep_252_clone_5.png
../testdata_color/t2cep_252_clone_6.png
../testdata_color/t2cep_252_clone_7.png
../testdata_color/t2cep_253.png
../testdata_color/t2cep_253_clone_0.png
../testdata_color/t2cep_253_clone_1.png
../testdata_color/t2cep_253_clone_2.png
../testdata_color/t2cep_253_clone_3.png
../testdata_color/t2cep_253_clone_4.png
../testdata_color/t2cep_253_clone_5.png
../testdata_color/t2cep_253_clone_6.png
../testdata_color/t2cep_254.png
../testdata_color/t2cep_254_clone_0.png
../testdata_color/t2cep_254_clone_1.png
../testdata_color/t2cep_254_clone_2.png
../testdata_color/t2cep_254_clone_3.png
../testdata_color/t2cep_254_clone_4.png
../testdata_color/t2cep_254_clone_5.png
../testdata_color/t2cep_254_clone_6.png
../testdata_color/t2cep_254_clone_7.png
../testdata_color/t2cep_255.png
../testdata_color/t2cep_255_clone_0.png
../testdata_color/t2cep_255_clone_1.png
../testdata_color/t2cep_

../testdata_color/t2cep_277_clone_3.png
../testdata_color/t2cep_277_clone_4.png
../testdata_color/t2cep_277_clone_5.png
../testdata_color/t2cep_277_clone_6.png
../testdata_color/t2cep_278.png
../testdata_color/t2cep_278_clone_0.png
../testdata_color/t2cep_278_clone_1.png
../testdata_color/t2cep_278_clone_2.png
../testdata_color/t2cep_278_clone_3.png
../testdata_color/t2cep_278_clone_4.png
../testdata_color/t2cep_278_clone_5.png
../testdata_color/t2cep_278_clone_6.png
../testdata_color/t2cep_278_clone_7.png
../testdata_color/t2cep_279.png
../testdata_color/t2cep_279_clone_0.png
../testdata_color/t2cep_279_clone_1.png
../testdata_color/t2cep_279_clone_2.png
../testdata_color/t2cep_279_clone_3.png
../testdata_color/t2cep_279_clone_4.png
../testdata_color/t2cep_279_clone_5.png
../testdata_color/t2cep_279_clone_6.png
../testdata_color/t2cep_280.png
../testdata_color/t2cep_280_clone_0.png
../testdata_color/t2cep_280_clone_1.png
../testdata_color/t2cep_280_clone_2.png
../testdata_color/t2cep_

In [20]:
prediction/len(datafiles)*100

array([[0.00, 0.00, 0.41, 0.00, 99.59]])

In [21]:
filtered_datafiles = np.copy(datafiles)

In [22]:
filtered_datafiles = [ x for x in filtered_datafiles if "clone" not in x ]

In [23]:
print(len(filtered_datafiles))
print(len(datafiles))

283
2441


In [24]:
prediction = np.array([0,0,0,0,0])
print(prediction)

for img in filtered_datafiles:
    print(img)
    img_size = 128
    # img = cv2.imread(img)
    # img = cv2.resize(img,(img_size,img_size))

    # img = np.expand_dims(img, axis=0)

    # model.predict(img)
    img = image.load_img(img, target_size=(img_size, img_size))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    print(model.predict(img))
    prediction = prediction + model.predict(img)
    # model.predict_classes(img)

print(prediction)

[0 0 0 0 0]
../testdata_color/t2cep_001.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_002.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_003.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_004.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_005.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_006.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_007.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_008.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_010.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_011.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_012.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_013.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_014.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_015.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_016.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_017.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_

../testdata_color/t2cep_140.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_141.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_142.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_143.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_144.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_145.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_146.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_147.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_148.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_149.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_151.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_152.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_153.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_154.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_155.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_156.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_

[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_279.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_280.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_281.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_282.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_283.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_284.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_285.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_286.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_287.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_288.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_289.png
[[0.00 0.00 0.00 0.00 1.00]]
../testdata_color/t2cep_290.png
[[0.00 0.00 0.00 0.00 1.00]]
[[0.00 0.00 1.00 0.00 282.00]]


In [25]:
prediction = prediction/len(filtered_datafiles)*100

In [26]:
prediction

array([[0.00, 0.00, 0.35, 0.00, 99.65]])